language: node_js
repo_token: BIMLvfwfjpmDo1TFIGBcvmki5gtlCtJsk
node_js:
- v10
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
script:
  - npm test -- -i
  - npm run coveralls

env:
  global:
  - CXX=g++-4.8
  - MASTER_KEY=masterKey
  - JWT_SECRET=jwtSecret
